# Generated by Django 4.2.2 on 2023-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_site', '0002_accountrecord_loan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='loan_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='principle_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
