# Generated by Django 4.2.2 on 2023-07-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_site', '0004_alter_accountrecord_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
